### ISSUE TITLE
Quantify member opinions on external relations with new CFES roadmap

### ISSUE THREAD

**Issue by eexie** [cfes-github/projects#10]
**What is the motivation for this project? What specific problem(s) might it solve?**
Make decisions related to our partnerships that are well-informed by the opinions of our members.

**Describe the solution and project outcomes you'd like**
Provide a framework for members to provide their perspective on external representation (to academic, national, or international partners) so that the federation can make informed decisions with our partners.
Framework should include a rough communication plan, and tool. Use Github projects to provide better visibility on the CFES goals and priorities, and allow members to upvote important projects

**Describe alternatives you've considered, or past work on this topic**
In the past, schedule and presentations has been sent to membership in advance, but this has seen low engagement. 

**List the stakeholders of this project**
VPI, VPA, President, International Working Group

**Proposed timeline**
- [x] present idea to team at Fall Meeting 2019
- [x] investigate tools (Tascade, Github Projects)
- [ ] present rough draft roadmap at pre-week
- [ ] trial tool leading up to spring meeting, transition with next year
- [ ] release tool to membership

**Additional context**
Add any other context about the project request here.
